# apiVersion: aws.crossplane.io/v1alpha1
# kind: StoreConfig
# metadata:
#   name: vault
#   labels:
#     {{- include "aws-provisioner-config.labels" . | nindent 4 }}    
# spec:
#   type: Vault
#   defaultScope: {{ .Release.Namespace }}
#   vault:
#     server: "https://vault.apps.rosa.fja-hcp.4j9x.p3.openshiftapps.com"
#     mountPath: crossplane/
#     version: v2
#     auth:
#       method: Token
#       token:
#         source: Filesystem
#         fs:
#           path: /vault/secrets/token